# Lecture 3: Scientific programming

## Content
 
* Summary of lecture 2
* `numpy`: 
    * the `array`
    * indexing
    * some standard operations/methods
    * linear algebra `<3`
* plotting with `matplotlib`
* `scipy`:
    * distributions
    * Nonlinear solvers
    * Nonlinear optimization

## Summary of lecture 2

* Collections: `tuple` & `dict`
* Mutabillity
* Loops: `for`
& `while` loop
* Functions

In [1]:
t = (2,3)

In [3]:
t

(2, 3)

In [5]:
type(t)

tuple

In [7]:
t[0] = 1

TypeError: 'tuple' object does not support item assignment

In [8]:
l = list(t)

In [9]:
l[1] = 1

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.

The `numpy` package (module) is used in almost all numerical computation using Python. It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

To use `numpy` you need to import the module, using for example:

In [14]:
import numpy as np

In [15]:
np.array(1)

array(1)

In [11]:
import numpy

In [12]:
numpy.array(1)

array(1)

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 



In [17]:
[1,2] + [2,3]

[1, 2, 2, 3]

In [18]:
np.array((1,2)) + np.array((2,3))

array([3, 5])

## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists/tuples

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [20]:
np.array([1,2,3])

array([1, 2, 3])

In [23]:
v = np.array((1,2,3))

In [24]:
M = np.array(((1,2),(3,4)))

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [26]:
type(v)

numpy.ndarray

In [27]:
type(M)

numpy.ndarray

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [29]:
v.shape

(3,)

Equivalently, we could use the function `numpy.shape`

In [31]:
np.shape(M)

(2, 2)

So far the `numpy.ndarray` looks awefully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type? 

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:

In [32]:
M.dtype

dtype('int64')

We get an error if we try to assign a value of the wrong type to an element in a numpy array:

In [34]:
M

array([[1, 2],
       [3, 4]])

In [38]:
M[0,0] = 0

In [40]:
M[1,1]

4

In [37]:
M[0,0] = 'hellooo'

ValueError: invalid literal for int() with base 10: 'hellooo'

### Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

#### `np.arange`

In [42]:
x = np.arange(0,10)

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(-1,2)

array([-1,  0,  1])

In [48]:
np.arange(-1,1,0.1) # arange(start, stop, step)

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

#### `np.linspace`

In [50]:
np.linspace(0,2,10) # linspace(start, stop, number)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

#### random data

In [53]:
np.random.rand(3,3) # draw 3x3 array from uniform distribution 0 to 1

array([[0.73455082, 0.00406553, 0.015099  ],
       [0.45806527, 0.14380166, 0.40173184],
       [0.43370044, 0.46289317, 0.35408678]])

In [61]:
np.random.randn(3,3) # draw 3x3 from standard normal

array([[-0.79758461,  1.77934297, -0.84400175],
       [ 0.33449603, -0.11293938, -0.29898686],
       [-1.50801561, -0.7851967 ,  0.10904272]])

In [63]:
stuff = [1,2,3,4,5,6]

In [65]:
np.random.choice(stuff)

1

#### zeros and ones

In [57]:
np.zeros(3)

array([0., 0., 0.])

In [59]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [60]:
np.ones(4)

array([1., 1., 1., 1.])

## Manipulating arrays

### Indexing

We can index elements in an array using square brackets and indices:

In [11]:
#

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [12]:
#

The same thing can be achieved with using `:` instead of an index: 

In [13]:
#

We can assign new values to elements in an array using indexing:

In [14]:
#

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [15]:
#

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [16]:
#

We can omit any of the three parameters in `M[lower:upper:step]`:

In [17]:
#

Negative indices counts from the end of the array (positive index from the begining):

In [18]:
#

Index slicing works exactly the same way for multidimensional arrays:

In [19]:
#

### Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [20]:
#

We can also use index masks: If the index mask is an Numpy array of data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element: 

In [21]:
#

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [22]:
#

`np.all` and `np.any`:

In [ ]:
#

## Some standard operations

Lets us create some very precious data that we want to learn more about.

In [23]:
#

#### sum

In [24]:
#

#### mean

In [25]:
#

#### standard deviations and variance

In [26]:
#

#### min and max

In [27]:
#

Many other functions and methods in the `array` and `matrix` classes accept the same (optional) `axis` keyword argument.

In [28]:
#

### Reshaping and stacking arrays

The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays. Let us create `A`.

In [30]:
#

## Copy and "deep copy"

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference). 

In [31]:
#

If we want to avoid this behavior, so that when we get a new completely independent object `B` copied from `A`, then we need to do a so-called "deep copy" using the function `copy`:

In [32]:
#

## Vectorization

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [81]:
#

### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the default behaviour is **element-wise** operations:

In [33]:
#

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [34]:
#

What about matrix mutiplication? There are two ways. We can either use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [35]:
#

See also the related functions: `inner`, `outer`, `cross`, `kron`, `tensordot`. Try for example `help(kron)`.

In [36]:
#

You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [37]:
#

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [38]:
#

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [39]:
#

#### `np.diag`

In [40]:
#

Let us experiment with matrices

$$ 
  A = \begin{bmatrix} 2 & -1 \\ 3 & 0 \end{bmatrix} 
  \quad \text{and} \quad
  b = \begin{bmatrix} 1 \\ 1 \end{bmatrix}
$$

In [319]:
A = [[2, -1],
     [3, 0]]
A = np.array(A) # Convert from list to NumPy array
b = np.ones((2, 1))  # Shape is 2 x 1

#### Inverse

In [42]:
#

#### Determinant

In [19]:
#

In [43]:
#

#### Eigenvalues and eigenvectors

In [41]:
#

Let us solve (for $x$) the problem 
$$A x = b$$

In [1]:
#

## Exercises

#### 1 Indexing
a) create an array `a` from 0 to 9

In [11]:
#

b) get only the first 3 values of `a`

In [12]:
#

c) create a random array `b` of size 9 with $b_i \sim N(0,1)$.

In [ ]:
#

d) get all the values of `b` that are larger than one.

In [13]:
#

#### 2 Standard operations
a) create a random array `b` of size 9 with $b_i \sim N(0,1)$.

In [14]:
#

b) get the lowest and highest value of `b`.

In [15]:
#

c) create an array `c` of size 9 and stack it horizontally on `b`. Call the result `d`.

In [17]:
#

d) get the mean of `d`.

In [18]:
#

e) create a null vector of size 10 but the fifth value which is 1

In [3]:
#

f) create a vector with values ranging from 10 to 49


In [2]:
#

g) reverse the vector (first element becomes last)

In [ ]:
#

h) create a 3x3 matrix with values ranging from 0 to 8 

In [ ]:
#

i) find indices of non-zero elements from [1,2,0,0,4,0] 

In [ ]:
#

j) create a 3x3 identity matrix 

In [1]:
#